name: Build and Deploy
on:
  push: 
    branches: [ main, feature/* ]

jobs:
  build-and-deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2.3.1
      
      - name: Install and Build 🔧
        env: 
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build
